### ISSUE TITLE
相机似乎被锁死了，如果我想要让相机变得可移动应该怎么操作

### ISSUE THREAD

**Issue by samo-c** [robinwood3d/UnrealTransformGizmo#6]
相机似乎被锁死了，如果我想要让相机变得可移动应该怎么操作

**Comment by robinwood3d** [comment]
你好，我这里示例中的Pawn是在按下拖拽时调用了Set Ignore Look Input节点使其视角锁死，因为拖拽时移动视角会出现坐标定位问题。
如果你一定要在拖拽时旋转视角，可以把示例中的Pawn蓝图中的Set Ignore Look Input节点全部删除
